<h2>Add product</h2>

<?php echo $this->tag->form("addProduct/register"); ?>

    <p>
        <label for="Name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="description">Description</label>
        <?php echo $this->tag->textArea("description"); ?>
    </p>

    <p>
        <label for="tags">Tags</label>
        <?php echo $this->tag->textField("tags"); ?>
    </p>

    <p>
        <label for="price">Price</label>
        <?php echo $this->tag->textField("price"); ?>
    </p>

    <p>
        <label for="stock">Stock</label>
        <?php echo $this->tag->textField("stock"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Add Product"); ?>
    </p>

</form>