<?php

echo "<h1>Product List!</h1>";

echo $this->tag->linkTo(["/", "Go Back!", 'class' => 'btn btn-primary']);

if ($product->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>product_id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Stock</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Products quantity: <?php echo $product->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($product as $p) { ?>
            <tr>
                <td><?php echo $p->product_id; ?></td>
                <td><?php echo $p->name; ?></td>
                <td><?php echo $p->description; ?></td>
                <td><?php echo $p->tags; ?></td>
                <td><?php echo $p->price; ?></td>
                <td><?php echo $p->stock; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}