<?php  //echo $_SERVER['REQUEST_URI'].'&locale=fr'; die;?>
<?php  //$url = $_SERVER['REQUEST_URI']."&locale=";?>

<form action="" method='get'>
<div for="drop down" style="padding-top: 40px;">
        <label for="role">Choose a Language:</label>

        <select name="locale" onchange = "this.form.submit()" >
            <option value="en">List</option>   
            <option value="en">English</option>
           <option value="fr">French</option>
           <option value="hn">Hindi</option>
           <input type="hidden" name="bearer" value="<?php echo $_GET['bearer']?>">
        </select>

</div>

</form>

<!-- <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div> -->


<?php

echo "<h1>".$this->locale->_('Hello World')."</h1>";

echo PHP_EOL;

echo $this->tag->linkTo(
    'addProduct',
    //'Add Product Here!',
    $this->locale->_('Add Product Here!')
);
echo "<br>";
echo $this->tag->linkTo(
    'addProduct/productlist',
    // 'Product List!'
    $this->locale->_('Product List!')
);
echo "<br>";

echo $this->tag->linkTo(
    'order',
    // 'Place Order!',
    $this->locale->_('Place Order!')
);

echo "<br>";

echo $this->tag->linkTo(
    'order/orderlist',
    // 'Order List!'
    $this->locale->_('Order List!')
);

echo "<br>";

echo $this->tag->linkTo(
    'setting',
    // 'Settings!'
    $this->locale->_('Settings!')
);
echo "<br>";

echo $this->tag->linkTo(
    'acl',
    // 'ACL !!'
    $this->locale->_('ACL !!')
);

echo "<br>";

echo $this->tag->linkTo(
    'signup',
    // 'Signup Here Buddy !!'
    $this->locale->_('Signup Here Buddy !!')
);
?>


