<h2>Signup Here</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">Email</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <div for="drop down">
        <label for="role">Choose a role:</label>

        <select name="role">
            <?php echo $options; ?>
        </select>

    </div>
    
    <p>
        <?php echo $this->tag->submitButton("Signup"); ?>
    </p>

</form>