

<h2>Place order</h2>

<?php echo $this->tag->form("order/register"); ?>

    <p>
        <label for="Name">Customer Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="address">Customer Addresss</label>
        <?php echo $this->tag->textArea("address"); ?>
    </p>

    <p>
        <label for="zipcode">Zipcode</label>
        <?php echo $this->tag->textField("zipcode"); ?>
    </p>

    <p>
        <label for="product">Select Product</label>
       

        <?php echo $this->tag->select(['product', Products::find(), 'using'=>['name', 'name']]); ?>
    </p>

    <p>
        <label for="quantity">Quantity</label>
        <?php echo $this->tag->textField("quantity"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("order"); ?>
    </p>

</form>