<div style="margin:40px">
    <form action="/acl/permission" method="post">
    <div for="drop down">
        <label for="role">Choose a role:</label>

        <select name="role">
            <?php echo $options; ?>
        </select>

    </div>
    <div for="components">

        <h1>Show Checkboxes</h1>

            <!-- <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
            <label for="vehicle1"> I have a bike</label><br>
            <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
            <label for="vehicle2"> I have a car</label><br>
            <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">
            <label for="vehicle3"> I have a boat</label><br><br>
            <input type="submit" value="Submit"> -->
            <?php echo $checkbox ?>
            <input type="submit" value="Submit">
            
            
    </div>
    </form>
</div>